#!/usr/bin/env rake

require 'bundler/setup'

app = ENV['APP']

unless app
  raise ArgumentError,
    "The APP environment variable must be set to 'engine' or 'ui' to specify which application should host firewall_egress."
end

APP_RAKEFILE = File.expand_path("../../../#{app}/Rakefile", __FILE__)

load 'rails/tasks/engine.rake'

# Depend on app:db:test:prepare so that test database is recreated just like in a full rails app
# @see http://viget.com/extend/rails-engine-testing-with-rspec-capybara-and-FactoryBot
RSpec::Core::RakeTask.new(spec: 'app:db:test:prepare')

task :default => :spec
