json.id                   workspace.id
json.name                 workspace.name
json.boundary             workspace.boundary
json.description          workspace.description
json.owner_id             workspace.owner_id
json.limit_to_network     workspace.limit_to_network
json.created_at           workspace.created_at
json.updated_at           workspace.updated_at
json.import_fingerprint   workspace.import_fingerprint