json.id                      session.id
json.host_id                 session.host_id
json.stype                   session.stype
json.via_exploit             session.via_exploit
json.via_payload             session.via_payload
json.desc                    session.desc
json.port                    session.port
json.platform                session.platform
json.datastore               session.datastore
json.close_reason            session.close_reason
json.local_id                session.local_id
json.module_run_id           session.module_run_id
json.last_seen               session.last_seen
json.campaign_id             session.campaign_id
json.opened_at               session.opened_at
json.closed_at               session.closed_at
