json.id                           host.id
json.created_at                   host.created_at
json.address                      host.address
json.mac                          host.mac
json.comm                         host.comm
json.name                         host.name
json.state                        host.state
json.os_name                      host.os_name
json.os_flavor                    host.os_flavor
json.os_sp                        host.os_sp
json.os_lang                      host.os_lang
json.arch                         host.arch
json.workspace_id                 host.workspace_id
json.updated_at                   host.updated_at
json.purpose                      host.purpose
json.info                         host.info
json.comments                     host.comments
json.scope                        host.scope
json.virtual_host                 host.virtual_host
json.note_count                   host.note_count
json.vuln_count                   host.vuln_count
json.service_count                host.service_count
json.host_detail_count            host.host_detail_count
json.exploit_attempt_count        host.exploit_attempt_count
json.cred_count                   host.cred_count
json.history_count                host.history_count
json.detected_arch                host.detected_arch
json.os_family                    host.os_family