json.id                         web_vuln.id
json.web_site_id                web_vuln.web_site_id
json.path                       web_vuln.path
json.method                     web_vuln.method
json.params                     web_vuln.params
json.pname                      web_vuln.pname
json.risk                       web_vuln.risk
json.name                       web_vuln.name
json.query                      web_vuln.query
json.legacy_category            web_vuln.legacy_category
json.confidence                 web_vuln.confidence
json.description                web_vuln.description
json.blame                      web_vuln.blame
json.request                    web_vuln.request
json.owner                      web_vuln.owner
json.payload                    web_vuln.payload
json.request_id                 web_vuln.request_id
json.category_id                web_vuln.category_id
json.created_at                 web_vuln.created_at
json.updated_at                 web_vuln.updated_at
